### ISSUE TITLE
(Issue) Event created with very long date is not compatible

### ISSUE THREAD

**Issue by chsainikhilreddy** [AkhilReddy1998/CountDownTimerApp#3]
If you pick a year after **10000**, the event countdown gives NaN.

**Comment by Akhil-Reddy-Challa** [comment]
It makes no sense to pick an Year greater than 5000 (App is working as expected)
It displays NaN as the time in the Box
>>No Fix can be deployed
Instead we can display a message saying the eventDate is too far.
