### ISSUE TITLE
(Issue) Negative timer is displayed after reloading a page with finished Count down

### ISSUE THREAD

**Issue by chsainikhilreddy** [AkhilReddy1998/CountDownTimerApp#4]
![timer_bug](https://user-images.githubusercontent.com/60440700/97106008-10cb1a80-16e5-11eb-9cf0-04ef3f2739bd.JPG)

**Comment by Akhil-Reddy-Challa** [comment]
Fixed this buggy behaviour on version_3 commit on 28th Oct

**Comment by Akhil-Reddy-Challa** [comment]
>>Old Fix: Above BUG was fixed using the below logic
While reading data from DB, we perform a check on the eventTime, if it is not a future time we ignore it
Issues:
1) We dont get a chance to display the event has complete, we will simply ignore it.
>>User would have no idea on the finished events(Bad UX)
2) While reading events data from DB, we just ignore the past events
>>These events are staled out in the DB.

>>Better Fix:
1) Validate the event date in CountDownTimer file and change the eventBox to Complete if the date is behind.

**Comment by Akhil-Reddy-Challa** [comment]
Fixed the issue on 28Oct with commit msg("fixed Issue#4, organised code in CountDownTimer File")
